services:
  fastapi-server:
    build: app/
    container_name: fastapi-server
    volumes:
      - ~/.aws:/root/.aws
      - ./app:/app
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: app/
          target: app/
          ignore:
            - venv/
            - __pycache__/
        - action: rebuild
          path: app/requirements.txt
          target: app/
      restart: always

  
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis




  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest

    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    privileged: true

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.17.4
#    ports:
#      - "5044:5044"
#    volumes:
#      - ./elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#      - ./elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.17.4
#    ports:
#      - "5601:5601"
#    environment:
#      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
#
#  filebeat:
#    image: docker.elastic.co/beats/filebeat:7.17.4
#    volumes:
#      - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml  # 경로 수정
#      - ./app/logs:/app/logs:ro
#    depends_on:
#      - logstash
