version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  fastapi-server:
    build: app/
    container_name: fastapi-server
    ports:
      - "8000:8000"
    volumes:
      - ~/.aws:/root/.aws
    restart: always
