global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi-server:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']