{
 "title": "get",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "1분당 http요청 수 ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!=\"/metrics\"}[1m]))\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP delete",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(http_requests_total{method=\"DELETE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOTAL HTTP ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{handler!=\"/metrics\"})\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP put",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(http_requests_total{method=\"PUT\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP get",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{method=\"GET\", handler!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "\bHTTP post ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{method=\"POST\"}) by (endpoint)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}